### ISSUE TITLE
Two conflicting filetypes do not defer to whichever has a firstLineMatch

### ISSUE THREAD

**Issue by samcv** [atom/first-mate#85]
When two grammars have the same file extension, we should defer to whichever has firstLineMatch.

**Comment by Ingramz** [comment]
@samcv in the context of Atom, `first-mate` does not decide what language is being used for a document.

Atom's [grammar-registry](https://github.com/Ingramz/atom/blob/master/src/grammar-registry.coffee#L47-L55) deals with this in following manner:
* User overridden grammar (via ctrl/cmd+shift+l) is preferred for a document over automatically detected grammar.
* Longest file extension in `fileTypes` list will give the grammar a base score of it's length, if no extension has been detected, it will default to -1. If the file type matched, but was user defined in config (there used to be a way of doing this, not sure if relevant today), it gets additional 0.5 in the score to overrule stock file types.
* If base score by now is greater than 0 (at least 1 character extension detected) and grammar is part of user installed package, score gets additional 0.25 added to it, which makes it prefer user installed packages over core packages.
* If grammar has firstLineMatch and the file contents match the firstLineMatch, the score gets additional 0.125. Reasoning behind why firstLineMatch is used as a last resort is due to the fact that we want to rely on file extension before taking the contents into account

My guess is that your issue is coming from the fact that one package is core package and other one is user-installed, so the 0.25 will overpower 0.125. If you can provide the use case where this feels wrong, could you elaborate a little the use case where you are experiencing this?

**Comment by samcv** [comment]
I am the developer of the Perl 6 grammar for Atom https://github.com/perl6/atom-language-perl6
If I specify the `pm` extension, it will choose the Perl 6 grammar over the Perl grammar, even though it matches the Perl first line but doesn't match the Perl 6 first line. For this reason I have not added this as one of the extensions in the grammar. It would be nice if firstLineMatch was checked before scoring core vs non-core packages (in case both HAVE a firstLineMatch section), otherwise if both match or both don't match, we can fallback to choosing core vs user-installed.

**Comment by Ingramz** [comment]
Swapping last two weights make sense in this case and doesn't seem to break the behavior compared to current scheme. I'll craft a PR and link it here. Thank you for your input.

**Comment by samcv** [comment]
@Ingramz any progress? Thanks :-)

**Comment by Ingramz** [comment]
@samcv there is not much I can do about it, I have proposed a change in form of PR and it's really up to Atom maintainers to approve this. I will rebase that pull request to get a more recent build out of the CI, so it would be possible to test this by anyone interested and give feedback, which will encourage maintainers to merge that pull request.

**Comment by samcv** [comment]
Great, I am willing to test it out. Let me know when you rebase it.

**Comment by Ingramz** [comment]
@samcv I already rebased it yesterday, you can find build artifacts from CI output (at least for Windows). No idea if or where other platform artifacts are stored.

**Comment by 50Wliu** [comment]
atom/atom#13597 has been merged.
